# Generated by Django 4.0.4 on 2022-05-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Storing', models.TextField()),
                ('Supply', models.TextField()),
                ('Retailing', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=3000, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Faqing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Faqs', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField(blank=True, default=0, null=True)),
                ('General_name', models.CharField(max_length=200, null=True)),
                ('Popular_name', models.CharField(max_length=200, null=True)),
                ('Size', models.IntegerField(blank=True, default=0, null=True)),
                ('Price', models.IntegerField(blank=True, default=0, null=True)),
                ('Percent', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_name', models.CharField(max_length=20, null=True)),
                ('Service_details', models.CharField(max_length=2000, null=True)),
                ('Benefit_head', models.CharField(max_length=20, null=True)),
                ('Benefit_daetails', models.CharField(max_length=3000, null=True)),
                ('Service2_name', models.CharField(max_length=20, null=True)),
                ('Service2_details', models.CharField(max_length=2000, null=True)),
                ('Benefit2_head', models.CharField(max_length=20, null=True)),
                ('Benefit2_daetails', models.CharField(max_length=3000, null=True)),
                ('Service3_name', models.CharField(max_length=20, null=True)),
                ('Service3_details', models.CharField(max_length=2000, null=True)),
                ('Benefit3_head', models.CharField(max_length=20, null=True)),
                ('Benefit3_daetails', models.CharField(max_length=3000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.TextField()),
            ],
        ),
    ]
